In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv("datalr.csv")

In [3]:
data.head(15)

AT      V       AP     RH      PE
0   14.96  41.76  1024.07  73.17  463.26
1   25.18  62.96  1020.04  59.08  444.37
2    5.11  39.40  1012.16  92.14  488.56
3   20.86  57.32  1010.24  76.64  446.48
4   10.82  37.50  1009.23  96.62  473.90
5   26.27  59.44  1012.23  58.77  443.67
6   15.89  43.96  1014.02  75.24  467.35
7    9.48  44.71  1019.12  66.43  478.42
8   14.64  45.00  1021.78  41.25  475.98
9   11.74  43.56  1015.14  70.72  477.50
10  17.99  43.72  1008.64  75.04  453.02
11  20.14  46.93  1014.66  64.22  453.99
12  24.34  73.50  1011.31  84.15  440.29
13  25.71  58.59  1012.77  61.83  451.28
14  26.19  69.34  1009.48  87.59  433.99

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9568 entries, 0 to 9567
Data columns (total 5 columns):
AT    9568 non-null float64
V     9568 non-null float64
AP    9568 non-null float64
RH    9568 non-null float64
PE    9568 non-null float64
dtypes: float64(5)
memory usage: 373.9 KB


In [5]:
X=data.iloc[:,0:4].values
y=data.iloc[:,4].values

In [6]:
print(X)
print(y)
y=y.reshape(len(y),1)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [15]:
from sklearn.preprocessing import StandardScaler
ss_X=StandardScaler()
ss_y=StandardScaler()
X=ss_X.fit_transform(X)
y=ss_y.fit_transform(y)

In [16]:
print(X)
print(y)

[[-0.62951938 -0.98729659  1.8204884  -0.00951935]
 [ 0.74190911  0.68104512  1.1418628  -0.97462052]
 [-1.95129733 -1.17301765 -0.18507756  1.2898397 ]
 ...
 [ 1.56583973  1.57581141 -0.05709854 -2.52261812]
 [ 0.64797565  1.19177803  0.1011913  -0.74790051]
 [ 0.26150656  0.64641916  0.66867722 -0.37254534]]
[[ 0.52120807]
 [-0.58566442]
 [ 2.00367889]
 ...
 [-1.45288056]
 [-1.09134518]
 [-0.06357687]]


In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.25, random_state=0)

In [18]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [27]:
ss_y.inverse_transform(lr.predict(ss_X.transform(X_test)))
#ss_y.inverse_transform(lr.predict(ss_X.transform([[14.96,1.76,024.07,3.17]])))

array([[-1.34362365],
       [ 0.24670072],
       [ 0.49226467],
       ...,
       [ 1.13581458],
       [ 1.23489515],
       [-0.72350434]])

In [28]:
y_pred=lr.predict(X_test)

In [29]:
from sklearn.metrics import r2_score

In [30]:
r2_score(y_test,y_pred)

0.9323789104734466