In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv("data.csv")

In [3]:
data.head(15)

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0              1000025                5                        1   
1              1002945                5                        4   
2              1015425                3                        1   
3              1016277                6                        8   
4              1017023                4                        1   
5              1017122                8                       10   
6              1018099                1                        1   
7              1018561                2                        1   
8              1033078                2                        1   
9              1033078                4                        2   
10             1035283                1                        1   
11             1036172                2                        1   
12             1041801                5                        3   
13             1043999                1                        1   
14             1044572                8                        7   

    Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                          1                  1                            2   
1                          4                  5                            7   
2                          1                  1                            2   
3                          8                  1                            3   
4                          1                  3                            2   
5                         10                  8                            7   
6                          1                  1                            2   
7                          2                  1                            2   
8                          1                  1                            2   
9                          1                  1                            2   
10                         1                  1                            1   
11                         1                  1                            2   
12                         3                  3                            2   
13                         1                  1                            2   
14                         5                 10                            7   

    Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0             1                3                1        1      2  
1            10                3                2        1      2  
2             2                3                1        1      2  
3             4                3                7        1      2  
4             1                3                1        1      2  
5            10                9                7        1      4  
6            10                3                1        1      2  
7             1                3                1        1      2  
8             1                1                1        5      2  
9             1                2                1        1      2  
10            1                3                1        1      2  
11            1                2                1        1      2  
12            3                4                4        1      4  
13            3                3                1        1      2  
14            9                5                5        4      4

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 683 entries, 0 to 682
Data columns (total 11 columns):
Sample code number             683 non-null int64
Clump Thickness                683 non-null int64
Uniformity of Cell Size        683 non-null int64
Uniformity of Cell Shape       683 non-null int64
Marginal Adhesion              683 non-null int64
Single Epithelial Cell Size    683 non-null int64
Bare Nuclei                    683 non-null int64
Bland Chromatin                683 non-null int64
Normal Nucleoli                683 non-null int64
Mitoses                        683 non-null int64
Class                          683 non-null int64
dtypes: int64(11)
memory usage: 58.8 KB


In [5]:
X=data.iloc[:,1:10].values
y=data.iloc[:,10].values

In [6]:
print(X)

[[ 5  1  1 ...  3  1  1]
 [ 5  4  4 ...  3  2  1]
 [ 3  1  1 ...  3  1  1]
 ...
 [ 5 10 10 ...  8 10  2]
 [ 4  8  6 ... 10  6  1]
 [ 4  8  8 ... 10  4  1]]


In [7]:

y=y.reshape(len(y),1)
print(y)

[[2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [2]
 [4]
 [4]
 [2]
 [2]
 [4]
 [2]
 [4]
 [4]
 [2]
 [2]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [2]
 [2]
 [2]
 [4]
 [2]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [2]
 [4]
 [2]
 [2]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [2]
 [4]
 [4]
 [2]
 [4]
 [2]
 [4]
 [4]
 [2]
 [2]
 [4]
 [2]
 [4]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [4]
 [4]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [4]
 [4]
 [4]
 [2]
 [4]
 [4]
 [4]
 [4]
 [4]
 [2]
 [4]
 [2]
 [4]
 [4]
 [4]
 [2]
 [2]
 [2]
 [4]
 [2]
 [2]
 [2]
 [2]
 [4]
 [4]
 [4]
 [2]
 [4]
 [2]
 [4]
 [2]
 [2]
 [2]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [2]
 [2]
 [4]
 [2]
 [2]
 [4]
 [2]
 [4]
 [4]
 [2]
 [2]
 [4]
 [2]
 [2]
 [4]
 [4]
 [2]
 [2]
 [2]
 [2]
 [4]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [4]
 [4]
 [2]
 [4]
 [2]
 [4]
 [2]
 [2]
 [2]
 [4]
 [4]
 [2]
 [4]
 [4]
 [4]
 [2]
 [4]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [4]
 [2]
 [2]
 [2]
 [4]


In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.25, random_state=0)

In [9]:
print(X_train)

[[ 7  6 10 ...  9 10  2]
 [ 8  3  8 ...  8  9  8]
 [ 8 10 10 ... 10 10  1]
 ...
 [ 1  1  1 ...  1  1  1]
 [ 3  1  1 ...  2  1  1]
 [10  9  7 ...  7  7  1]]


In [10]:
print(X_test)

[[1 1 1 ... 1 1 1]
 [3 1 1 ... 2 1 1]
 [5 5 5 ... 4 3 1]
 ...
 [5 1 1 ... 3 1 2]
 [2 2 2 ... 7 1 1]
 [2 1 1 ... 3 1 1]]


In [11]:
print(y_test)

[[2]
 [2]
 [4]
 [4]
 [2]
 [2]
 [2]
 [4]
 [2]
 [2]
 [4]
 [2]
 [4]
 [2]
 [2]
 [2]
 [4]
 [4]
 [4]
 [2]
 [2]
 [2]
 [4]
 [2]
 [4]
 [4]
 [2]
 [2]
 [2]
 [4]
 [2]
 [4]
 [4]
 [2]
 [2]
 [2]
 [4]
 [4]
 [2]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [2]
 [2]
 [4]
 [2]
 [4]
 [2]
 [2]
 [2]
 [4]
 [2]
 [2]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [2]
 [2]
 [2]
 [4]
 [2]
 [4]
 [2]
 [2]
 [4]
 [2]
 [2]
 [4]
 [2]
 [4]
 [2]
 [4]
 [4]
 [4]
 [2]
 [4]
 [4]
 [4]
 [2]
 [2]
 [2]
 [4]
 [4]
 [2]
 [2]
 [4]
 [4]
 [2]
 [2]
 [4]
 [2]
 [2]
 [4]
 [2]
 [2]
 [2]
 [4]
 [2]
 [2]
 [2]
 [4]
 [2]
 [2]
 [4]
 [4]
 [2]
 [4]
 [2]
 [4]
 [2]
 [2]
 [4]
 [2]
 [2]
 [4]
 [2]
 [4]
 [2]
 [2]
 [2]
 [4]
 [2]
 [2]
 [2]
 [2]
 [4]
 [2]
 [4]
 [2]
 [4]
 [4]
 [2]
 [2]
 [2]
 [2]
 [4]
 [4]
 [2]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]]


In [12]:
print(y_train)

[[4]
 [4]
 [4]
 [2]
 [2]
 [2]
 [4]
 [2]
 [2]
 [4]
 [4]
 [2]
 [4]
 [2]
 [2]
 [4]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [4]
 [2]
 [4]
 [2]
 [2]
 [2]
 [4]
 [2]
 [2]
 [2]
 [2]
 [4]
 [4]
 [2]
 [2]
 [4]
 [4]
 [2]
 [2]
 [4]
 [4]
 [2]
 [4]
 [2]
 [4]
 [4]
 [2]
 [2]
 [2]
 [4]
 [2]
 [4]
 [2]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [2]
 [2]
 [4]
 [2]
 [2]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [2]
 [2]
 [4]
 [2]
 [4]
 [2]
 [2]
 [4]
 [4]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [2]
 [2]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [2]
 [2]
 [2]
 [4]
 [4]
 [2]
 [4]
 [2]
 [2]
 [2]
 [4]
 [2]
 [2]
 [2]
 [4]
 [4]
 [2]
 [4]
 [2]
 [2]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [4]
 [4]
 [4]
 [2]
 [4]
 [2]
 [4]
 [2]
 [4]
 [4]
 [4]
 [2]
 [2]
 [4]
 [2]
 [2]
 [2]
 [2]
 [4]
 [4]
 [2]
 [2]
 [2]
 [4]
 [2]
 [2]
 [4]
 [2]
 [2]
 [2]
 [2]
 [4]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [2]
 [4]
 [2]


In [13]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [14]:
y_pred=lr.predict(X_test)

In [15]:
print(y_pred)

[[2.27374812]
 [2.02601278]
 [3.5411669 ]
 [3.71291054]
 [1.89221609]
 [2.10056498]
 [2.24839585]
 [3.92050761]
 [2.07805338]
 [1.92736391]
 [3.98236463]
 [2.15674528]
 [4.15816246]
 [2.02601278]
 [2.19268188]
 [2.68132894]
 [3.55895579]
 [4.12967771]
 [4.17839279]
 [2.15606992]
 [2.02601278]
 [2.08937141]
 [3.13737861]
 [1.99086497]
 [3.78963453]
 [3.90536558]
 [2.19921385]
 [1.9055024 ]
 [2.08951384]
 [3.69869244]
 [1.89221609]
 [4.289563  ]
 [4.57354973]
 [2.0611606 ]
 [2.0401894 ]
 [2.0611606 ]
 [3.85278671]
 [3.63225146]
 [2.0401894 ]
 [3.88244434]
 [2.25192661]
 [2.41433938]
 [2.01362218]
 [1.95786786]
 [1.89221609]
 [2.11924508]
 [1.96277023]
 [4.20621621]
 [2.11758221]
 [2.08951384]
 [3.78534167]
 [2.14589136]
 [3.46569615]
 [2.10569874]
 [2.15606992]
 [2.32404528]
 [3.74764589]
 [3.49730146]
 [2.37703152]
 [3.89345869]
 [1.96251172]
 [1.9875991 ]
 [2.01183616]
 [1.99086497]
 [2.0611606 ]
 [1.96251172]
 [1.96251172]
 [2.0611606 ]
 [3.64378932]
 [2.80601624]
 [1.94306804]
 [2.02

In [16]:
from sklearn.metrics import r2_score

In [17]:
r2_score(y_test,y_pred)

0.8048430228780002

In [19]:
lr.predict([[5,1,1,1,2,1,3,1,1]])

array([[2.15980947]])