In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
data=pd.read_csv("Datalr.csv")

In [6]:
data.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 683 entries, 0 to 682
Data columns (total 11 columns):
Sample code number             683 non-null int64
Clump Thickness                683 non-null int64
Uniformity of Cell Size        683 non-null int64
Uniformity of Cell Shape       683 non-null int64
Marginal Adhesion              683 non-null int64
Single Epithelial Cell Size    683 non-null int64
Bare Nuclei                    683 non-null int64
Bland Chromatin                683 non-null int64
Normal Nucleoli                683 non-null int64
Mitoses                        683 non-null int64
Class                          683 non-null int64
dtypes: int64(11)
memory usage: 58.8 KB


dependent and independent variable decrlation

In [7]:
X=data.iloc[:,0:4].values
y=data.iloc[:,4].values

In [8]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [12]:
print(y)
y=y.reshape(len(y),1)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


Modelling with sklearn

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.25, random_state=0)

scaling the data

In [14]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
X_test=ss.fit_transform(X_test)
X_train=ss.fit_transform(X_train)
y_test=ss.fit_transform(y_test)
y_train=ss.fit_transform(y_train)

In [15]:
print(X_test)
print(X_train)
print(y_test)
print(y_train)

[[ 1.2066454   1.877152   -0.61316986 -0.29564748]
 [-0.28659552 -0.36869872  1.38854238  0.76998964]
 [-0.63653212 -0.86017515  1.00327559  1.7770374 ]
 ...
 [-0.87561095 -1.22740635  0.32487103 -1.10969499]
 [-1.36846059 -0.7319981   1.20428435  0.82030757]
 [ 0.81530408  0.97991262 -0.52774113 -1.19861296]]
[[-0.73379745 -0.90698189  3.1525588  -0.25305966]
 [ 1.2271277   1.11220399 -0.04249709 -0.71444278]
 [-0.68675675 -0.9982979   0.89543906  0.51317809]
 ...
 [-0.38300823 -1.24862972  0.84145712  0.13108451]
 [-0.92196025 -1.04080708  1.54490924  0.88160106]
 [ 1.70156675  1.06418436 -1.21323035 -2.41711739]]
[[-1.35595699]
 [ 0.3245754 ]
 [ 0.39055878]
 ...
 [ 0.84368357]
 [ 1.13564541]
 [-1.01494555]]
[[ 0.83853602]
 [-1.28041725]
 [-0.01150918]
 ...
 [ 0.27418579]
 [ 0.49183022]
 [-1.53795337]]


TRAINING THE DATA

In [17]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [18]:
y_pred=lr.predict(X_test)

In [19]:
print(y_pred)

[[-1.34353632]
 [ 0.23863963]
 [ 0.48143144]
 ...
 [ 1.12774805]
 [ 1.22205595]
 [-0.72396593]]


In [20]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.932355461417621