In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
data=pd.read_csv("Datalr.csv")

In [4]:
data.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [6]:
X=data.iloc[:,0:4].values
y=data.iloc[:,4].values

In [8]:
print(X)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [10]:
y=y.reshape(len(y),1)

In [11]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
ss_X=ss.fit_transform(X)
ss_y=ss.fit_transform(y)

In [12]:
print(ss_X)

[[-0.62951938 -0.98729659  1.8204884  -0.00951935]
 [ 0.74190911  0.68104512  1.1418628  -0.97462052]
 [-1.95129733 -1.17301765 -0.18507756  1.2898397 ]
 ...
 [ 1.56583973  1.57581141 -0.05709854 -2.52261812]
 [ 0.64797565  1.19177803  0.1011913  -0.74790051]
 [ 0.26150656  0.64641916  0.66867722 -0.37254534]]


In [13]:
print(ss_y)

[[ 0.52120807]
 [-0.58566442]
 [ 2.00367889]
 ...
 [-1.45288056]
 [-1.09134518]
 [-0.06357687]]
