In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv("data.csv")

In [3]:
data.head(15)

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0              1000025                5                        1   
1              1002945                5                        4   
2              1015425                3                        1   
3              1016277                6                        8   
4              1017023                4                        1   
5              1017122                8                       10   
6              1018099                1                        1   
7              1018561                2                        1   
8              1033078                2                        1   
9              1033078                4                        2   
10             1035283                1                        1   
11             1036172                2                        1   
12             1041801                5                        3   
13             1043999                1                        1   
14             1044572                8                        7   

    Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                          1                  1                            2   
1                          4                  5                            7   
2                          1                  1                            2   
3                          8                  1                            3   
4                          1                  3                            2   
5                         10                  8                            7   
6                          1                  1                            2   
7                          2                  1                            2   
8                          1                  1                            2   
9                          1                  1                            2   
10                         1                  1                            1   
11                         1                  1                            2   
12                         3                  3                            2   
13                         1                  1                            2   
14                         5                 10                            7   

    Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0             1                3                1        1      2  
1            10                3                2        1      2  
2             2                3                1        1      2  
3             4                3                7        1      2  
4             1                3                1        1      2  
5            10                9                7        1      4  
6            10                3                1        1      2  
7             1                3                1        1      2  
8             1                1                1        5      2  
9             1                2                1        1      2  
10            1                3                1        1      2  
11            1                2                1        1      2  
12            3                4                4        1      4  
13            3                3                1        1      2  
14            9                5                5        4      4

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 683 entries, 0 to 682
Data columns (total 11 columns):
Sample code number             683 non-null int64
Clump Thickness                683 non-null int64
Uniformity of Cell Size        683 non-null int64
Uniformity of Cell Shape       683 non-null int64
Marginal Adhesion              683 non-null int64
Single Epithelial Cell Size    683 non-null int64
Bare Nuclei                    683 non-null int64
Bland Chromatin                683 non-null int64
Normal Nucleoli                683 non-null int64
Mitoses                        683 non-null int64
Class                          683 non-null int64
dtypes: int64(11)
memory usage: 58.8 KB


In [5]:
X=data.iloc[:,1:10].values
y=data.iloc[:,10].values

In [6]:
print(X)

[[ 5  1  1 ...  3  1  1]
 [ 5  4  4 ...  3  2  1]
 [ 3  1  1 ...  3  1  1]
 ...
 [ 5 10 10 ...  8 10  2]
 [ 4  8  6 ... 10  6  1]
 [ 4  8  8 ... 10  4  1]]


In [7]:

y=y.reshape(len(y),1)
print(y)
y=ss.fit_transform(y)

[[2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [2]
 [4]
 [4]
 [2]
 [2]
 [4]
 [2]
 [4]
 [4]
 [2]
 [2]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [2]
 [2]
 [2]
 [4]
 [2]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [2]
 [4]
 [2]
 [2]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [2]
 [4]
 [4]
 [2]
 [4]
 [2]
 [4]
 [4]
 [2]
 [2]
 [4]
 [2]
 [4]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [4]
 [4]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [4]
 [4]
 [4]
 [2]
 [4]
 [4]
 [4]
 [4]
 [4]
 [2]
 [4]
 [2]
 [4]
 [4]
 [4]
 [2]
 [2]
 [2]
 [4]
 [2]
 [2]
 [2]
 [2]
 [4]
 [4]
 [4]
 [2]
 [4]
 [2]
 [4]
 [2]
 [2]
 [2]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [2]
 [2]
 [4]
 [2]
 [2]
 [4]
 [2]
 [4]
 [4]
 [2]
 [2]
 [4]
 [2]
 [2]
 [4]
 [4]
 [2]
 [2]
 [2]
 [2]
 [4]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [4]
 [4]
 [2]
 [4]
 [2]
 [4]
 [2]
 [2]
 [2]
 [4]
 [4]
 [2]
 [4]
 [4]
 [4]
 [2]
 [4]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [4]
 [2]
 [2]
 [2]
 [4]


NameError: name 'ss' is not defined

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.25, random_state=0)

In [ ]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
X_train=ss.fit_transform(X_train)
X_test=ss.fit_transform(X_test)
#y_test=ss.fit_transform(y_test)

In [ ]:
print(X_train)

In [ ]:
print(X_test)

In [ ]:
print(y_test)

In [ ]:
print(y_train)